// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTt8KPpPfozTzBl5WSs6EaF4w6gDEfkeU',
    appId: '1:149112746740:web:e358d5c2611c47193f24a1',
    messagingSenderId: '149112746740',
    projectId: 'noteapp-d9cf1',
    authDomain: 'noteapp-d9cf1.firebaseapp.com',
    storageBucket: 'noteapp-d9cf1.firebasestorage.app',
    measurementId: 'G-NGCTQDMTVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqSvLSB19PgyJ4J8n26MkerWmap_x40dw',
    appId: '1:149112746740:android:708772acb6f4bd6b3f24a1',
    messagingSenderId: '149112746740',
    projectId: 'noteapp-d9cf1',
    storageBucket: 'noteapp-d9cf1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2ZqXlfuPRIxd55l-uBb-nHF-zyht0g24',
    appId: '1:149112746740:ios:1abf39d7946f24e53f24a1',
    messagingSenderId: '149112746740',
    projectId: 'noteapp-d9cf1',
    storageBucket: 'noteapp-d9cf1.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2ZqXlfuPRIxd55l-uBb-nHF-zyht0g24',
    appId: '1:149112746740:ios:1abf39d7946f24e53f24a1',
    messagingSenderId: '149112746740',
    projectId: 'noteapp-d9cf1',
    storageBucket: 'noteapp-d9cf1.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTt8KPpPfozTzBl5WSs6EaF4w6gDEfkeU',
    appId: '1:149112746740:web:c76b5a31b56258f83f24a1',
    messagingSenderId: '149112746740',
    projectId: 'noteapp-d9cf1',
    authDomain: 'noteapp-d9cf1.firebaseapp.com',
    storageBucket: 'noteapp-d9cf1.firebasestorage.app',
    measurementId: 'G-58MZQPL5ZW',
  );
}
